### PR TITLE
Add  Testing Framework with tests

### PR DESCRIPTION
**Pull request by ashwinimanoj**
Added Mocha as testing framework and SinonJS for mocks and stubs.

### CODE REVIEW

**Comment by aphelionz** [comment]
Looks like a great start. Do you want to roll out a few more tests and we can see how it looks?

**Comment by ashwinimanoj** [comment]
@aphelionz Sure! Could you give me some more context into what the results passed to reporter looks like?

**Comment by aphelionz** [comment]
Absolutely. Also, paging @mistakia, the original author, to this thread. In the meantime, this should get you started. (Just thinking out loud here and I'm totally open to suggestions.)

- Just to follow convention in other repos, create two js files `test/cli.spec.js` and `test/reporter.spec.js`.
- In `test/cli.spec.js` we're _really_ just making sure all of the command line options work. There's a bunch of posts about doing this with `yargs`, pick your poison :skull: 
- In `test/reporter.spec.js`, I think your best bet is to create a bunch of fixture input that the exported `reporter` function can handle, and just make sure that the code there is as covered as it can be!
- I think you'll need to update the test command to expose garbage collection. I believe it's just `mocha --expose-gc`.

Hope this helps, and thank you so much for wanting to contribute.

**Comment by ashwinimanoj** [comment]
@aphelionz Sure! This can help me get started with the tests. I haven't really tested command line options before, but I will look into it! Also, shall I add istanbul to check code coverage? I am very happy to contribute! Thanks!

**Comment by aphelionz** [comment]
Istanbul isn't a priority over simply having the tests, so I'm fine with or without it :+1:

**Comment by ashwinimanoj** [comment]
> * Just to follow convention in other repos, create two js files `test/cli.spec.js` and `test/reporter.spec.js`.

Done!

> * In `test/cli.spec.js` we're _really_ just making sure all of the command line options work. There's a bunch of posts about doing this with `yargs`, pick your poison 💀

Done! I tried covering all scenarios I could think of.

> * In `test/reporter.spec.js`, I think your best bet is to create a bunch of fixture input that the exported `reporter` function can handle, and just make sure that the code there is as covered as it can be!

I need help with what reporter expects, I am not sure what the fields expected in each object are. Is there somewhere I can look into to get more context on this?

> * I think you'll need to update the test command to expose garbage collection. I believe it's just `mocha --expose-gc`.

Done!

**Comment by RichardLitt** [comment]
Closes #4. 

Thanks for your work, @ashwinimanoj!

**Comment by aphelionz** [comment]
@ashwinimanoj I'm trying to get @mistakia to weigh in here on the reporting but if we don't hear from them soon I can get you some fixture data :+1: Thanks again

**Comment by ashwinimanoj** [comment]
@aphelionz Sure! That would be great. You can get it to me whenever, I can wait. Thanks!

**Comment by aphelionz** [comment]
@ashwinimanoj Finally looking at this. Thank you for your patience! I noticed that some tests are failing. I think this might be intentional so I wanted to check.

image

Do we need to write proper event handlers? :) Happy to do so if need be.

**Comment by ashwinimanoj** [comment]
@aphelionz This is what I see when I run the tests. Could you tell me how to replicate what you are seeing?
Screenshot 2019-12-28 at 10 47 11 AM

Also, what message does it show when the assertions fail?

**Comment by aphelionz** [comment]
My mistake. Setting the `LANG=en_US` fixed it

image

**Comment by ashwinimanoj** [comment]
I have updated the tests to check for help output if args are not passed, that should fix it. The tests should not have hardcoded strings, my mistake actually. Thanks for your help @aphelionz :)

**Comment by mistakia** [comment]
@ashwinimanoj hey 👋

`results` passed to reporter is made up of an array of objects that looks like the following:
```
{
    name: "Benchmark name",
    cpus: os.cpus(),
    loadavg: os.loadavg(),
    elapsed: <integer>
    stats: { count: <integer> } // number of iterations/cycles
    memory: { before: process.memoryUsage(), after: process.memoryUsage() }
}
```

For more information, check out https://github.com/orbitdb/benchmark-runner/blob/master/cli.js#L131-L139

`runOne` returns an object for each benchmark, which is then put into an array and sent to the `reporter`.

**Pull request merged**
